name: Daily Linode Cleanup
on:
  schedule:
    # runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install the Linode CLI
        uses: linode/action-linode-cli@e8752ed165037e5fa726df38db787e74bb745237 # v1.1.0
        with:
          token: ${{ secrets.LINODE_CLI_TOKEN }}
      - name: List Linodes to Delete
        env:
          USER_INITIALS: ${{ secrets.USER_INITIALS }}
        run: linode-cli linodes list --text | awk -v initials="${USER_INITIALS}" 'NR>1 && tolower($2) ~ tolower(initials) {print $1}' > linode-ids-delete.txt
      - name: Delete Linodes
        run: while read id; do linode-cli linodes delete "$id"; done < linode-ids-delete.txt
