name: Daily Linode Cleanup
on:
  schedule:
    # runs every hour
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  job-name:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Linode cli
        uses: brendon1555/setup-linode-cli@master
        with:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      - run: linode-cli linodes list --tags ${{ secrets.DELETE_TAG }}  --text |  awk '(NR>1)' | awk  '{print $1}' > linode-ids-delete.txt
      - run: ./delete.sh
